version: "3"

services:

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app/public:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: ${APP_NAME}-php
    build: docker/
    restart: unless-stopped
    ports:
      - "9092:9001"
    working_dir: /var/www
    volumes:
      - ./app/public:/var/www
      - ./docker/php/php.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: ${APP_NAME}-db
    image: library/mysql:8.0.19
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3320:3306"
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: php-docker-template
      MYSQL_ROOT_PASSWORD: 12345678
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    tmpfs:
      - /var/lib/mysql
